# Generated by Django 3.2.9 on 2022-10-27 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InfoUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField()),
                ('login', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('birth', models.DateField()),
                ('tg', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
            ],
        ),
    ]
