# Generated by Django 3.2.9 on 2022-10-28 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='infouser',
            name='over_18',
            field=models.BooleanField(default=False),
        ),
    ]
