# Generated by Django 3.2.9 on 2022-10-28 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infouser',
            name='birth',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='infouser',
            name='phone',
            field=models.CharField(max_length=50),
        ),
    ]
