# Generated by Django 3.2.9 on 2022-10-29 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_infouser_over_18'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infouser',
            name='birth',
            field=models.DateField(),
        ),
    ]
